config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  
  resources :todos, only: [:index, :new, :create, :show]

  resource :session, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/user.rb
class User
  def initialize(email)
    @email = email
  end

  def todos
    Todo.where(email: @email)
  end

  def signed_in?
    @email.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate
    if !signed_in?
      redirect_to new_session_path
    end
  end
  def signed_in?
    current_user.signed_in?
  end

  def current_email
    session[:current_email]
  end

  def sign_in_as email
    session[:current_email] = email
  end

  def current_user
    User.new(current_email)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    sign_in_as params[:session][:email]
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate

  def index
  @todos = current_user.todos
  end
  def new
    @todo = Todo.new
  end

  def create
    current_user.todos.create todo_params
    redirect_to root_path
  end

  private
  
  def todo_params
    params.require(:todo).permit(:task)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Todos</h1>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<%= link_to 'Add a new task', new_todo_path %>
<ul class="todos">
    <% @todos.each do |todo| %>
        <li>
            <%= todo.task %>
        </li>
    <% end %>
</ul>

app/views/todos/new.html.erb
<%= form_for @todo do |f| %>
    <%= f.label :task %>
    <%= f.text_field :task %>

    <%= f.submit 'Add task'%>
<% end %>